openapi: "3.0.0"

info:
  version: 1.0.0
  title: Product Rest APId
  description: API Rest definition to manage products

servers:
  - url: http://localhost:8080
    description: Local

security:
  - BearerAuth: []

tags:
  - name: Products
    description: Section of the products

  - name: Product reviews
    description: Section of the product reviews

paths:
  /v1/products:
    get:
      operationId: search-products
      summary: Search products
      description: Search products
      tags:
        - Products
      parameters:
        - name: pageNumber
          in: query
          required: false
          schema:
            type: integer
          description: Number of the page
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
          description: Size of the page
        - name: order
          in: query
          schema:
            $ref: './products.yml#/components/schemas/ProductFilterOrder'
          description: Order of the result
          required: false
        - name: ascending
          in: query
          required: false
          schema:
            type: boolean
          description: Return data using ascending order
        - name: name
          in: query
          required: false
          schema:
            type: string
          description: Name of the product
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './products.yml#/components/schemas/ProductSummary'
        default:
          $ref: './shared.yml#/components/responses/ProblemDetailsResponse'

    post:
      operationId: create-product
      summary: Create product
      description: Create product
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './products.yml#/components/schemas/CreateProductInput'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './products.yml#/components/schemas/Product'
        default:
          $ref: './shared.yml#/components/responses/ProblemDetailsResponse'

  /v1/products/{productCode}:
    get:
      operationId: get-product
      summary: Get product
      description: Get product
      tags:
        - Products
      parameters:
        - $ref: './products.yml#/components/parameters/productCodePath'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './products.yml#/components/schemas/Product'
        default:
          $ref: './shared.yml#/components/responses/ProblemDetailsResponse'

    put:
      operationId: update-product
      summary: Update product
      description: Update product
      tags:
        - Products
      parameters:
        - $ref: './products.yml#/components/parameters/productCodePath'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './products.yml#/components/schemas/UpdateProductInput'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './products.yml#/components/schemas/Product'
        default:
          $ref: './shared.yml#/components/responses/ProblemDetailsResponse'

    delete:
      operationId: delete-product
      summary: Delete product
      description: Delete product
      tags:
        - Products
      parameters:
        - $ref: './products.yml#/components/parameters/productCodePath'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './products.yml#/components/schemas/Product'
        default:
          $ref: './shared.yml#/components/responses/ProblemDetailsResponse'

  /v1/products/{productCode}/published:
    put:
      operationId: publish-product
      summary: Publish product
      description: Publish product
      tags:
        - Products
      parameters:
        - $ref: './products.yml#/components/parameters/productCodePath'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './products.yml#/components/schemas/Product'
        default:
          $ref: './shared.yml#/components/responses/ProblemDetailsResponse'

  /v1/products/{productCode}/unpublished:
    put:
      operationId: unpublish-product
      summary: Unpublish product
      description: Unpublish product
      tags:
        - Products
      parameters:
        - $ref: './products.yml#/components/parameters/productCodePath'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './products.yml#/components/schemas/Product'
        default:
          $ref: './shared.yml#/components/responses/ProblemDetailsResponse'

  /v1/products/{productCode}/reviews:
    post:
      operationId: create-product-review
      summary: Create product review
      description: Create product review
      tags:
        - Product reviews
      parameters:
        - $ref: './products.yml#/components/parameters/productCodePath'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './product-reviews.yml#/components/schemas/CreateProductReviewInput'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './product-reviews.yml#/components/schemas/ProductReview'
        default:
          $ref: './shared.yml#/components/responses/ProblemDetailsResponse'

    get:
      operationId: search-product-reviews
      summary: Search product reviews
      description: Search product reviews
      tags:
        - Product reviews
      parameters:
        - $ref: './products.yml#/components/parameters/productCodePath'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './product-reviews.yml#/components/schemas/ProductReview'
        default:
          $ref: './shared.yml#/components/responses/ProblemDetailsResponse'

  /v1/products/{productCode}/reviews/{username}:
    get:
      operationId: get-product-review
      summary: Get product review
      description: Get product review
      tags:
        - Product reviews
      parameters:
        - $ref: './products.yml#/components/parameters/productCodePath'
        - $ref: './users.yml#/components/parameters/usernamePath'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './product-reviews.yml#/components/schemas/ProductReview'
        default:
          $ref: './shared.yml#/components/responses/ProblemDetailsResponse'

    put:
      operationId: update-product-review
      summary: Update product review
      description: Update product review
      tags:
        - Product reviews
      parameters:
        - $ref: './products.yml#/components/parameters/productCodePath'
        - $ref: './users.yml#/components/parameters/usernamePath'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './product-reviews.yml#/components/schemas/UpdateProductReviewInput'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './product-reviews.yml#/components/schemas/ProductReview'
        default:
          $ref: './shared.yml#/components/responses/ProblemDetailsResponse'

    delete:
      operationId: delete-product-review
      summary: Delete product review
      description: Delete product review
      tags:
        - Product reviews
      parameters:
        - $ref: './products.yml#/components/parameters/productCodePath'
        - $ref: './users.yml#/components/parameters/usernamePath'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './product-reviews.yml#/components/schemas/ProductReview'
        default:
          $ref: './shared.yml#/components/responses/ProblemDetailsResponse'

components:

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT security

