components:

  parameters:
    productReviewIdPath:
      name: productReviewId
      in: path
      description: Product review id
      required: true
      schema:
        type: string
      example: '123456789:00001'

  schemas:
    CreateProductReviewInput:
      type: object
      description: Create product review input
      required:
        - productCode
        - comment
      properties:
        productCode:
          type: string
          description: Product code to create a review
          example: '00001'
        comment:
          type: string
          description: Comment of the review
          example: 'One comment of the product'

    UpdateProductReviewInput:
      type: object
      description: Update product review input
      required:
        - comment
      properties:
        comment:
          type: string
          description: Comment of the review
          example: 'One comment of the product'

    ProductReviewId:
      type: object
      description: Product review
      required:
        - productCode
        - username
      properties:
        productCode:
          type: string
          example: '123456789'
        username:
          type: string
          example: 'johndoe'

    ProductReview:
      type: object
      description: Product review
      required:
        - id
        - locale
        - comment
      properties:
        id:
          $ref: '#/components/schemas/ProductReviewId'
        locale:
          type: string
          description: Localization of the review
          example: 'en-US'
        comment:
          type: string
          description: Comment of the review
          example: 'One comment of the product'

    ProductReviewList:
      type: object
      required:
        - pageNumber
        - pageSize
        - totalItems
        - items
      properties:
        pageNumber:
          type: integer
          description: Number of total pages
        pageSize:
          type: integer
          description: Size of each page
        totalItems:
          type: integer
          description: Number of total items
        items:
          type: array
          items:
            $ref: '#/components/schemas/ProductReview'
