components:
  parameters:
    productCodePath:
      name: productCode
      in: path
      description: Product code
      required: true
      schema:
        type: string
      example: '123456789'

  schemas:
    ProductFilterOrder:
      type: string
      description: order of the product listing
      enum:
        - 'NAME'
        - 'TYPE_ID'
      x-enum-varnames:
        - NAME
        - TYPE_ID

    ProductStatus:
      type: string
      description: status of the product
      enum:
        - 'PUBLISHED'
        - 'UNPUBLISHED'
      x-enum-varnames:
        - PUBLISHED
        - UNPUBLISHED

    Product:
      type: object
      description: Product information
      required:
        - code
        - typeId
        - name
        - status
      properties:
        code:
          type: string
          description: Identifier of product
          example: '123456789'
        typeId:
          type: string
          description: Identifier of the product type
          example: 'fruit'
        name:
          type: object
          additionalProperties:
            type: string
          description: Name of the product
          example:
            es: 'Manzana'
            en: 'Apple'
        status:
          $ref: '#/components/schemas/ProductStatus'

    ProductSummary:
      type: object
      description: Product summary information
      required:
        - code
        - name
        - status
      properties:
        code:
          type: string
          description: Identifier of product
          example: '123456789'
        typeId:
          type: string
          description: Identifier of the product type
          example: 'fruit'
        name:
          type: object
          additionalProperties:
            type: string
          description: Name of the product
          example:
            es: 'Manzana'
            en: 'Apple'
        status:
          $ref: '#/components/schemas/ProductStatus'

    CreateProductInput:
      type: object
      description: Create product input
      required:
        - typeId
        - name
      properties:
        typeId:
          type: string
          description: Identifier of the product type
          example: 'fruit'
        name:
          type: object
          additionalProperties:
            type: string
          description: Name of the product
          example:
            es: 'Manzana'
            en: 'Apple'

    UpdateProductInput:
      type: object
      description: Create product input
      required:
        - name
      properties:
        name:
          type: object
          additionalProperties:
            type: string
          description: Name of the product
          example:
            es: 'Manzana'
            en: 'Apple'
