name: 'Increase version'

inputs:
  properties_path:
    description: "Gradle path to override version"
    default: "gradle.properties"

  version:
    description: "Type of version to generate"
    required: true
    type: choice
    options:
      - "release"
      - "hotfix"
      - "snapshot"

  git_user_name:
    description: "Name of the user who commits changes"
    default: "github-bot"

  git_user_email:
    description: "Email of the user who commits changes"
    default: "github-bot@fake.email.com"

outputs:
  version:
    description: "New generated version"
    value: ${{ steps.increase-version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Install asdf
      uses: ./.github/actions/asdf-install

    - name: Increase version
      id: increase-version
      shell: bash
      run: |
        NEW_VERSION = $(poetry run src/increase_version.py)
        
        echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

    - name: Configure Git
      shell: bash
      run: |
        git config user.name "${{ inputs.git_user_name }}"
        git config user.email "${{ inputs.git_user_email }}"

    - name: Commit new version
      shell: bash
      run: |
        git add *
        git commit -m "Update version ${{ steps.increase-version.outputs.version }}"
        
        git push
