name: 'Increase version'

inputs:
  properties-path:
    description: "Gradle path to override version"
    default: "gradle.properties"

  type:
    description: "Type of version to generate"
    required: true
    type: choice
    options:
      - "release"
      - "hotfix"
      - "snapshot"

  git-user-name:
    description: "Name of the user who commits changes"
    default: "github-bot"

  git-user-email:
    description: "Email of the user who commits changes"
    default: "github-bot@fake.email.com"

outputs:
  version:
    description: "New generated version"
    value: ${{ steps.increase-version.outputs.version }}

runs:
  using: 'node20'
  main: "dist/index.js"

    - name: Configure Git
      shell: bash
      run: |
        git config user.name "${{ inputs.git_user_name }}"
        git config user.email "${{ inputs.git_user_email }}"

    - name: Commit new version
      shell: bash
      run: |
        git add *
        git commit -m "Update version ${{ steps.increase-version.outputs.version }}"
        
        git push
