[project]
name = "increase-version"
version = "0.1.0"
description = ""
authors = []
requires-python = ">=3.13,<4.0"

[tool.poetry]
packages = [
    { include = "src" }
]

[tool.poetry.dependencies]
jproperties = "^2.1.2"
