spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081

  data:
    mongodb:
      uri: mongodb://root:root@127.0.0.1:27017/products?authSource=admin

components:
  rest:
    security:
      issuer: "products"
      duration: 7D
      password: "123456"
