
name: 'deploy'

on:
#  pull_request:
#    types:
#      - closed
#    branches:
#      - main
#      - master
#      - develop
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install asdf
        uses: ./.github/actions/asdf-install.yml

      - name: Build
        working-directory: code
        run: gradle build -x test
        env:
          # disable default JVM in container
          JAVA_HOME: ""

      - name: Upload compiled output in artifact
        uses: actions/upload-artifact@v4
        with:
          name: ms-build
          path: code/build/

  deploy-java:
    name: Deploy Jar
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install asdf
        uses: ./.github/actions/asdf-install.yml

      - name: Download compiled output from artifact
        uses: actions/download-artifact@v4
        with:
          name: ms-build
          path: code/build/

      - name: Deploy Jar
        working-directory: code
        run: |
          # Update step to deploy jar in the artifactory of the company
          echo "Deploy Jar"
