
name: 'pr-check'

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - code/**
      - apis/**

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install asdf
        uses: ./.github/workflows/asdf-install.yml

      - name: Build
        working-directory: code
        run: gradle build -x test
        env:
          # disable default JVM in container
          JAVA_HOME: ""

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install asdf
        uses: ./.github/workflows/asdf-install.yml

      - name: Test
        working-directory: code
        run: gradle test
        env:
          # disable default JVM in container
          JAVA_HOME: ""
